# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TC_TLAG
                                 A QGIS plugin
 Calculate the Time of Concentration and Lag Time
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-10
        copyright            : (C) 2019 by Jorge Andrés Herrera Maldonado
        email                : joaherrerama@unal.edu.co
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TC_TLAG class from file TC_TLAG.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Tc_Tlag import TC_TLAG
    return TC_TLAG(iface)
